# Generated by Django 5.0.6 on 2024-07-05 20:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("style_of_runner", models.CharField(max_length=100)),
                ("race_type", models.CharField(max_length=100)),
                ("goal_distance", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "goal_time",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                ("race_date", models.DateField(default=datetime.date.today)),
                ("race_name", models.CharField(default="Unknown Race", max_length=100)),
                (
                    "current_weekly_mileage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_weekly_mileage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "longest_run_last_4_weeks",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "current_running_days_per_week",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "willing_running_days_per_week",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "longest_run_day",
                    models.CharField(
                        blank=True, default="Monday", max_length=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_distance", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "pr_time",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="run_it.runner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(default=datetime.date.today)),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("race_name", models.CharField(default="Unknown Race", max_length=100)),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="run_it.runner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_weekly_mileage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "current_weekly_elevation",
                    models.CharField(default="0", max_length=100),
                ),
                (
                    "goal_race_distance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("goal_race_pace", models.CharField(default="00:00", max_length=100)),
                ("training_duration_weeks", models.IntegerField(default=0)),
                ("available_training_days_per_week", models.IntegerField(default=0)),
                ("strength_training", models.BooleanField(default=False)),
                ("rest_days", models.IntegerField(default=0)),
                ("injury_prevention", models.TextField(blank=True, null=True)),
                (
                    "runner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="run_it.runner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(default="Unknown", max_length=20)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="run_it.trainingplan",
                    ),
                ),
            ],
        ),
    ]
