# Generated by Django 5.0.6 on 2024-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runner",
            name="style_of_runner",
        ),
        migrations.AlterField(
            model_name="runner",
            name="current_running_days_per_week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runner",
            name="current_weekly_mileage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="runner",
            name="goal_time",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="runner",
            name="longest_run_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="runner",
            name="max_weekly_mileage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="runner",
            name="race_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="runner",
            name="race_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="runner",
            name="willing_running_days_per_week",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
