# Generated by Django 5.0.6 on 2024-07-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0002_remove_runner_style_of_runner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner",
            name="race_type",
            field=models.CharField(
                choices=[("Marathon", "Marathon"), ("Half Marathon", "Half Marathon")],
                max_length=20,
            ),
        ),
    ]
