# Generated by Django 5.0.6 on 2024-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0003_alter_runner_race_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner",
            name="goal_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
