# Generated by Django 5.0.6 on 2024-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0004_alter_runner_goal_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="distance_unit",
            field=models.CharField(
                choices=[("miles", "Miles"), ("kilometers", "Kilometers")],
                default="miles",
                max_length=10,
            ),
        ),
    ]
