# Generated by Django 5.0.6 on 2024-07-05 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0005_runner_distance_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="user",
            field=models.OneToOneField(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runner_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="runner",
            name="goal_distance",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="runner",
            name="race_type",
            field=models.CharField(max_length=100),
        ),
    ]
