# Generated by Django 5.0.6 on 2024-07-05 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0006_runner_user_alter_runner_goal_distance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runner_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
