# Generated by Django 5.0.6 on 2024-07-10 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run_it", "0007_alter_runner_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalrecord",
            name="race_distance",
        ),
        migrations.RemoveField(
            model_name="runner",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="runner",
            name="goal_distance",
        ),
        migrations.RemoveField(
            model_name="runner",
            name="phone",
        ),
        migrations.AddField(
            model_name="personalrecord",
            name="race_type",
            field=models.CharField(default="Marathon", max_length=100),
        ),
        migrations.AddField(
            model_name="runner",
            name="weeks_able_to_train",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalrecord",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prs",
                to="run_it.runner",
            ),
        ),
        migrations.AlterField(
            model_name="runner",
            name="longest_run_last_4_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runner",
            name="race_type",
            field=models.CharField(default="Marathon", max_length=100),
        ),
    ]
